version: '3.7'

services:
  phpfpm:
    container_name: napp_phpfpm
    build:
      context: ./php
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      - default
    expose:
      - 9000
    links:
      - redis
    environment:
      # The "redis" matches the name of the container defined below
      REDIS_HOST: redis
      REDIS_PORT: 6379

  database:
    image: mariadb:10.7.1
    container_name: napp_database
    restart: always
    ports:
      - "${DB_PORT:-4306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  admin
      MYSQL_USER:           borz
      MYSQL_PASSWORD:       123
      MYSQL_DATABASE:       test
    networks:
      - default
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: napp_phpmyadmin
    links:
      - database:db
    environment:
      MYSQL_ROOT_PASSWORD: 123
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - default

  nginx:
    container_name: napp_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm
      - database
    networks:
      - default

  redis:
    image: "redis:alpine"
    command: redis-server
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

#  redis:
#    image: redis:7.0-rc1
#    hostname: redis
#    volumes:
#      - "./volumes/redis:/data"

networks:
  default:
    driver: bridge

volumes:
  db-data:
  redis-data:
  redis-conf: